# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plp/proto/Dashboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plp/proto/Dashboard.proto',
  package='plp.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19plp/proto/Dashboard.proto\x12\tplp.proto\"X\n\x10\x44\x61shboardRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\x13\x63lassificationLimit\x18\x0f \x01(\x05\x12\x1b\n\x13\x64\x61shboardResultType\x18\x05 \x01(\t\"N\n\x11\x44\x61shboardResponse\x12\x0f\n\x06status\x18\xc8\x01 \x01(\x05\x12\x1a\n\x12\x63lassificationName\x18\x05 \x01(\t\x12\x0c\n\x04text\x18\n \x03(\t2c\n\x10\x44\x61shboardService\x12O\n\x10getDashboardData\x12\x1b.plp.proto.DashboardRequest\x1a\x1c.plp.proto.DashboardResponse\"\x00\x62\x06proto3'
)




_DASHBOARDREQUEST = _descriptor.Descriptor(
  name='DashboardRequest',
  full_name='plp.proto.DashboardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='plp.proto.DashboardRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classificationLimit', full_name='plp.proto.DashboardRequest.classificationLimit', index=1,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dashboardResultType', full_name='plp.proto.DashboardRequest.dashboardResultType', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=128,
)


_DASHBOARDRESPONSE = _descriptor.Descriptor(
  name='DashboardResponse',
  full_name='plp.proto.DashboardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='plp.proto.DashboardResponse.status', index=0,
      number=200, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classificationName', full_name='plp.proto.DashboardResponse.classificationName', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='plp.proto.DashboardResponse.text', index=2,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['DashboardRequest'] = _DASHBOARDREQUEST
DESCRIPTOR.message_types_by_name['DashboardResponse'] = _DASHBOARDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DashboardRequest = _reflection.GeneratedProtocolMessageType('DashboardRequest', (_message.Message,), {
  'DESCRIPTOR' : _DASHBOARDREQUEST,
  '__module__' : 'plp.proto.Dashboard_pb2'
  # @@protoc_insertion_point(class_scope:plp.proto.DashboardRequest)
  })
_sym_db.RegisterMessage(DashboardRequest)

DashboardResponse = _reflection.GeneratedProtocolMessageType('DashboardResponse', (_message.Message,), {
  'DESCRIPTOR' : _DASHBOARDRESPONSE,
  '__module__' : 'plp.proto.Dashboard_pb2'
  # @@protoc_insertion_point(class_scope:plp.proto.DashboardResponse)
  })
_sym_db.RegisterMessage(DashboardResponse)



_DASHBOARDSERVICE = _descriptor.ServiceDescriptor(
  name='DashboardService',
  full_name='plp.proto.DashboardService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=210,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='getDashboardData',
    full_name='plp.proto.DashboardService.getDashboardData',
    index=0,
    containing_service=None,
    input_type=_DASHBOARDREQUEST,
    output_type=_DASHBOARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DASHBOARDSERVICE)

DESCRIPTOR.services_by_name['DashboardService'] = _DASHBOARDSERVICE

# @@protoc_insertion_point(module_scope)
