# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PermissionDisplay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PermissionDisplay.proto',
  package='plp.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17PermissionDisplay.proto\x12\tplp.proto\"+\n\x18PermissionDisplayRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\")\n\x19PermissionDisplayResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2|\n\x18PermissionDisplayService\x12`\n\x11PermissionDisplay\x12#.plp.proto.PermissionDisplayRequest\x1a$.plp.proto.PermissionDisplayResponse\"\x00\x62\x06proto3'
)




_PERMISSIONDISPLAYREQUEST = _descriptor.Descriptor(
  name='PermissionDisplayRequest',
  full_name='plp.proto.PermissionDisplayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='plp.proto.PermissionDisplayRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=81,
)


_PERMISSIONDISPLAYRESPONSE = _descriptor.Descriptor(
  name='PermissionDisplayResponse',
  full_name='plp.proto.PermissionDisplayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='plp.proto.PermissionDisplayResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['PermissionDisplayRequest'] = _PERMISSIONDISPLAYREQUEST
DESCRIPTOR.message_types_by_name['PermissionDisplayResponse'] = _PERMISSIONDISPLAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PermissionDisplayRequest = _reflection.GeneratedProtocolMessageType('PermissionDisplayRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONDISPLAYREQUEST,
  '__module__' : 'PermissionDisplay_pb2'
  # @@protoc_insertion_point(class_scope:plp.proto.PermissionDisplayRequest)
  })
_sym_db.RegisterMessage(PermissionDisplayRequest)

PermissionDisplayResponse = _reflection.GeneratedProtocolMessageType('PermissionDisplayResponse', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONDISPLAYRESPONSE,
  '__module__' : 'PermissionDisplay_pb2'
  # @@protoc_insertion_point(class_scope:plp.proto.PermissionDisplayResponse)
  })
_sym_db.RegisterMessage(PermissionDisplayResponse)



_PERMISSIONDISPLAYSERVICE = _descriptor.ServiceDescriptor(
  name='PermissionDisplayService',
  full_name='plp.proto.PermissionDisplayService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=126,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='PermissionDisplay',
    full_name='plp.proto.PermissionDisplayService.PermissionDisplay',
    index=0,
    containing_service=None,
    input_type=_PERMISSIONDISPLAYREQUEST,
    output_type=_PERMISSIONDISPLAYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERMISSIONDISPLAYSERVICE)

DESCRIPTOR.services_by_name['PermissionDisplayService'] = _PERMISSIONDISPLAYSERVICE

# @@protoc_insertion_point(module_scope)
