# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PermissionDisplay_pb2 as PermissionDisplay__pb2


class PermissionDisplayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PermissionDisplay = channel.unary_unary(
                '/plp.proto.PermissionDisplayService/PermissionDisplay',
                request_serializer=PermissionDisplay__pb2.PermissionDisplayRequest.SerializeToString,
                response_deserializer=PermissionDisplay__pb2.PermissionDisplayResponse.FromString,
                )


class PermissionDisplayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PermissionDisplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionDisplayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PermissionDisplay': grpc.unary_unary_rpc_method_handler(
                    servicer.PermissionDisplay,
                    request_deserializer=PermissionDisplay__pb2.PermissionDisplayRequest.FromString,
                    response_serializer=PermissionDisplay__pb2.PermissionDisplayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plp.proto.PermissionDisplayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PermissionDisplayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PermissionDisplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plp.proto.PermissionDisplayService/PermissionDisplay',
            PermissionDisplay__pb2.PermissionDisplayRequest.SerializeToString,
            PermissionDisplay__pb2.PermissionDisplayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
