# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from plp.proto import PermissionPoll_pb2 as PermissionPoll__pb2


class PermissionPollServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PermissionPoll = channel.unary_unary(
                '/plp.proto.PermissionPollService/PermissionPoll',
                request_serializer=PermissionPoll__pb2.PermissionPollRequest.SerializeToString,
                response_deserializer=PermissionPoll__pb2.PermissionPollResponse.FromString,
                )


class PermissionPollServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PermissionPoll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionPollServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PermissionPoll': grpc.unary_unary_rpc_method_handler(
                    servicer.PermissionPoll,
                    request_deserializer=PermissionPoll__pb2.PermissionPollRequest.FromString,
                    response_serializer=PermissionPoll__pb2.PermissionPollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plp.proto.PermissionPollService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PermissionPollService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PermissionPoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plp.proto.PermissionPollService/PermissionPoll',
            PermissionPoll__pb2.PermissionPollRequest.SerializeToString,
            PermissionPoll__pb2.PermissionPollResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
